[mcp_servers.mysql]
command = "npx"
args = [
    "-y",
    "@benborber/mcp-server-mysql",
    "--host",
    "localhost",
    "--port",
    "3306",
    "--user",
    "root",
    "--password",
    "123456",
    "--database",
    "pdemo",
]
